# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MicroPython pre-compile (mpy files)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mpy-cross
        
    - name: Running mpy-cross for each file
      run: |
        mkdir mpy
        cd mpy
        for file in ../*.py
        do
          mpy-cross $file
        done
        cd ..
        
    - name: Push to MicroPython Editor
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'mpy/.'
        destination_repo: 'letssteam/micropython-editor-experimental'
        destination_folder: 'static/assets/fat'
        user_email: 'jjbaudin@gmail.com'
        user_name: 'Jonathan BAUDIN'
      
