# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MicroPython pre-compile (mpy files)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  COMPLETION_FILE: "completion.json"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mpy-cross
        
    - name: Running mpy-cross for each file
      run: |
        mkdir mpy
        for file in *.py
        do
          echo compiling $file...
          mpy-cross -o mpy/${file%%.*}.mpy $file
        done
        
    - name: Generate completion doc
      run: |
        res=$(python .github/workflows/generate_doc.py $(ls *.py))
        if [[ $? -eq 0 ]]
        then
          echo $res > $COMPLETION_FILE
        else
          echo "Failed to generate completion !" 1>&2
          echo $res 1>&2
          exit 1
        fi
        
    - name: Push to MPY to MicroPython Editor
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'mpy/.'
        destination_repo: 'letssteam/micropython-editor-experimental'
        destination_folder: 'static/assets/fat'
        user_email: 'jjbaudin@gmail.com'
        user_name: 'Jonathan BAUDIN'
        
    - name: Push to Completion to MicroPython Editor
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: ${{ COMPLETION_FILE }}
        destination_repo: 'letssteam/micropython-editor-experimental'
        destination_folder: 'static/assets/'
        user_email: 'jjbaudin@gmail.com'
        user_name: 'Jonathan BAUDIN'
      
